language: node_js
node_js: "14"

sudo: required

install: yarn

before_script: yarn start & sleep 5
script: yarn test

env:
  - PORT=3000
  - NODE_ENV="testing"
  - SECRET="randomHashSecret"

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
