module.exports = {
  'any.unknown': '{{#label}} não é permitido',
  'any.invalid': '{{#label}} contains an invalid value',
  'any.empty': '{{#label}} é obrigatório',
  'any.required': '{{#label}} é obrigatório',
  'any.allowOnly': '{{#label}} deve ser um dos valores {{#valids}}',
  'any.default': '{{#label}} threw an error when running default method',
  'any.only': '{{#label}} deve ser um valor entre {{#valids}}',
  'boolean.base': '{{#label}} deve ser um booleano',
  'number.base': '{{#label}} deve ser um número',
  'number.min': '{{#label}} deve ser maior ou igual que {{#limit}}',
  'number.max': '{{#label}} deve ser menor ou igual que {{#limit}}',
  'number.less': '{{#label}} deve ser menor que {{#limit}}',
  'number.greater': '{{#label}} deve ser maior que {{#limit}}',
  'number.float': '{{#label}} deve ser float ou double',
  'number.integer': '{{#label}} deve ser um inteiro',
  'number.negative': '{{#label}} must be a negative number',
  'number.positive': '{{#label}} must be a positive number',
  'number.precision': '{{#label}} must have no more than {{#limit}} decimal places',
  'number.ref': '{{#label}} references "{{#ref}}" which is not a number',
  'number.multiple': '{{#label}} must be a multiple of {{#multiple}}',
  'number.port': '{{#label}} must be a valid port',
  'string.base': '{{#label}} deve ser um texto',
  'string.required': '{{#label}} é obrigatório',
  'string.empty': '{{#label}} não pode ser vazio',
  'string.min': '{{#label}} deve ter pelo menos {{#limit}} caracteres',
  'string.max': '{{#label}} não pode ter mais que {{#limit}} caracteres',
  'string.length': '{{#label}} deve ter {{#limit}} caracteres',
  'string.alphanum': '{{#label}} deve conter apenas caracteres alfa-numericos',
  'string.token': '{{#label}} must only contain alpha-numeric and underscore characters',
  'string.regex': '{{#label}} com formato inválido',
  'string.email': '{{#label}} inválido',
  'string.uri': '{{#label}} must be a valid uri',
  'string.uriRelativeOnly': '{{#label}} must be a valid relative uri',
  'string.uriCustomScheme': '{{#label}} must be a valid uri with a scheme matching the {{#scheme}} pattern',
  'string.isoDate': '{{#label}} deve ser uma data ISO 8601 válida',
  'string.guid': '{{#label}} must be a valid GUID',
  'string.hex': '{{#label}} must only contain hexadecimal characters',
  'string.hexAlign': '{{#label}} hex decoded representation must be byte aligned',
  'string.base64': '{{#label}} must be a valid base64 string',
  'string.hostname': '{{#label}} must be a valid hostname',
  'string.normalize': '{{#label}} must be unicode normalized in the {{#form}} form',
  'string.lowercase': '{{#label}} must only contain lowercase characters',
  'string.uppercase': '{{#label}} must only contain uppercase characters',
  'string.trim': '{{#label}} must not have leading or trailing whitespace',
  'string.creditCard': '{{#label}} must be a credit card',
  'string.ref': '{{#label}} references "{{#ref}}" which is not a number',
  'date.base': '{{#label}} precisa ser uma data válida',
  'number.unsafe': '{{#label}} precisa ser um número válido',
  'array.min': '{{#label}} deve conter ao menos {{#limit}} items',
  'array.max': '{{#label}} deve conter no máximo {{#limit}} item'
}
